### ISSUE TITLE
Perl regex in makefile "illegal"?

### ISSUE THREAD

**Issue by stefanhusmann** [akkartik/wart#5]
Hello,
I maintain an AUR package (Aarch Linux User Repository) for wart at
```
https://aur.archlinux.org/packages/wart-git/
```
The build used to work, but this is not true anymore. The build fails with
``` 
==> Starting build()...
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/ { <-- HERE .*/ at -e line 1.
make: *** [makefile:11: function_list] Error 255
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
```
This is strange, as the makefile was not changed for years. The only thing is that the perl version changed. I have 5.26.0-1. 

The same happens on Alpine Linux, also with perl 5.26.0.

**Comment by akkartik** [comment]
I suspect what happened was that I pushed a trivial commit which triggered CI. Thanks for the report; it's good to know who's using my projects downstream. I'll investigate.

**Comment by akkartik** [comment]
Works with Perl 5.18.2. (I hadn't actually tried compiling the project last night.)

Now spinning up a new, more up-to-date VPS.

**Comment by akkartik** [comment]
I see a warning in Perl 5.24.1 (on OpenBSD 6.1)

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/ { <-- HERE .*/ at -e line 1.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^\s*void (.*)\(\) { <-- HERE $/ at -e line 1.
```

**Comment by akkartik** [comment]
Never mind, 5.26 only released this May. No distribution has it. Now building it from source.

**Comment by stefanhusmann** [comment]
Confirmed for Arch Linux.
